/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FooterPart: typeof import('./../components/footerPart.vue')['default']
    HeaderPart: typeof import('./../components/headerPart.vue')['default']
    MenuPart: typeof import('./../components/menuPart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WaitPage: typeof import('./../components/waitPage.vue')['default']
  }
}
